In [11]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv('../data/eda_fake_job_postings.csv')
print('Dataset loaded successfully.')
print('shape of the dataset before dropped columns:', df.shape)
df.head()

Dataset loaded successfully.
shape of the dataset before dropped columns: (17880, 16)

,job_id,location,department,salary_range,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,job_description,jd_char_len,jd_word_count
0,1,"US, NY, New York",Marketing,Unknown,0,1,0,Other,Internship,Unknown,Unknown,Marketing,0,NaN,0,0
1,2,"NZ, , Auckland",Success,Unknown,0,1,0,Full-time,Not Applicable,Unknown,Marketing and Advertising,Customer Service,0,Customer Service - Cloud Video Production 90 S...,6133,901
2,3,"US, IA, Wever",Unknown,Unknown,0,1,0,Unknown,Unknown,Unknown,Unknown,Unknown,0,NaN,0,0
3,4,"US, DC, Washington",Sales,Unknown,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,Account Executive - Washington DC Our passion ...,5462,709
4,5,"US, FL, Fort Worth",Unknown,Unknown,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,Bill Review Manager SpotSource Solutions LLC i...,3949,470

In [13]:
df.info()
print('Found some in job_description missing values.')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   location             17880 non-null  object
 2   department           17880 non-null  object
 3   salary_range         17880 non-null  object
 4   telecommuting        17880 non-null  int64
 5   has_company_logo     17880 non-null  int64
 6   has_questions        17880 non-null  int64
 7   employment_type      17880 non-null  object
 8   required_experience  17880 non-null  object
 9   required_education   17880 non-null  object
 10  industry             17880 non-null  object
 11  function             17880 non-null  object
 12  fraudulent           17880 non-null  int64
 13  job_description      8845 non-null   object
 14  jd_char_len          17880 non-null  int64
 15  jd_word_count        17880 non-null  int64
dtypes: int64(7), object(9)
memory usage: 2.2+ MB
Found some in job_description missing values.

In [14]:
# Handling missing values in 'job_description' column
df['job_description'] = df['job_description'].fillna("")
print('Missing values in job_description filled with empty strings.')

Missing values in job_description filled with empty strings.

In [15]:
df.info()
print('Missing values in job_description handled successfully.')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   location             17880 non-null  object
 2   department           17880 non-null  object
 3   salary_range         17880 non-null  object
 4   telecommuting        17880 non-null  int64
 5   has_company_logo     17880 non-null  int64
 6   has_questions        17880 non-null  int64
 7   employment_type      17880 non-null  object
 8   required_experience  17880 non-null  object
 9   required_education   17880 non-null  object
 10  industry             17880 non-null  object
 11  function             17880 non-null  object
 12  fraudulent           17880 non-null  int64
 13  job_description      17880 non-null  object
 14  jd_char_len          17880 non-null  int64
 15  jd_word_count        17880 non-null  int64
dtypes: int64(7), object(9)
memory usage: 2.2+ MB
Missing values in job_description handled successfully.

Conclusion based on EDA, I retained a minimal set of high-signal features including textual job descriptions, key binary indicators, and selected categorical attributes. I also included job description length as a structural feature and excluded high-cardinality or unstable variables to reduce noise and overfitting.

In [16]:
df = df.drop(
    columns=[
        'job_id',
        'location',
        'industry',
        'function',
        'required_education',
        'salary_range',
        'department',
        'jd_char_len'
    ],
    errors='ignore'
)
print('Columns dropped.')

Columns dropped.

In [17]:
print('Shape of the dataset after dropping columns:', df.shape)

Shape of the dataset after dropping columns: (17880, 8)

In [18]:
df.head()

,telecommuting,has_company_logo,has_questions,employment_type,required_experience,fraudulent,job_description,jd_word_count
0,0,1,0,Other,Internship,0,,0
1,0,1,0,Full-time,Not Applicable,0,Customer Service - Cloud Video Production 90 S...,901
2,0,1,0,Unknown,Unknown,0,,0
3,0,1,0,Full-time,Mid-Senior level,0,Account Executive - Washington DC Our passion ...,709
4,0,1,1,Full-time,Mid-Senior level,0,Bill Review Manager SpotSource Solutions LLC i...,470

Saving the cleaned dataset version 2

In [19]:
df.to_csv('../data/cleaned_fake_job_postings_v2.csv', index=False)
print('Cleaned data version 2 is saved to cleaned_fake_job_postings_v2.csv')

Cleaned data version 2 is saved to cleaned_fake_job_postings_v2.csv