In [37]:
import pandas as pd
import numpy as np

Loading data

In [38]:
df = pd.read_csv('../data/cleaned_fake_job_postings_v2.csv')
print('Dataset loaded successfully.')
print('shape of the dataset:', df.shape)
df.head()

Dataset loaded successfully.
shape of the dataset: (17880, 8)

,telecommuting,has_company_logo,has_questions,employment_type,required_experience,fraudulent,job_description,jd_word_count
0,0,1,0,Other,Internship,0,NaN,0
1,0,1,0,Full-time,Not Applicable,0,Customer Service - Cloud Video Production 90 S...,901
2,0,1,0,Unknown,Unknown,0,NaN,0
3,0,1,0,Full-time,Mid-Senior level,0,Account Executive - Washington DC Our passion ...,709
4,0,1,1,Full-time,Mid-Senior level,0,Bill Review Manager SpotSource Solutions LLC i...,470

In [39]:
df.info()
print('Found some in job_description missing values.')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   telecommuting        17880 non-null  int64
 1   has_company_logo     17880 non-null  int64
 2   has_questions        17880 non-null  int64
 3   employment_type      17880 non-null  object
 4   required_experience  17880 non-null  object
 5   fraudulent           17880 non-null  int64
 6   job_description      8845 non-null   object
 7   jd_word_count        17880 non-null  int64
dtypes: int64(5), object(3)
memory usage: 1.1+ MB
Found some in job_description missing values.

In [40]:
# Handling missing values in 'job_description' column
df['job_description'] = df['job_description'].fillna("")
print('Missing values in job_description filled with empty strings.')

Missing values in job_description filled with empty strings.

In [41]:
df['job_description'].isnull().sum()

0

In [42]:
df.head(10)

,telecommuting,has_company_logo,has_questions,employment_type,required_experience,fraudulent,job_description,jd_word_count
0,0,1,0,Other,Internship,0,,0
1,0,1,0,Full-time,Not Applicable,0,Customer Service - Cloud Video Production 90 S...,901
2,0,1,0,Unknown,Unknown,0,,0
3,0,1,0,Full-time,Mid-Senior level,0,Account Executive - Washington DC Our passion ...,709
4,0,1,1,Full-time,Mid-Senior level,0,Bill Review Manager SpotSource Solutions LLC i...,470
5,0,0,0,Unknown,Unknown,0,,0
6,0,1,1,Full-time,Mid-Senior level,0,"Head of Content (m/f) Founded in 2009, the Fon...",336
7,0,1,1,Unknown,Unknown,0,Lead Guest Service Specialist Airenvy’s mis...,710
8,0,1,1,Full-time,Associate,0,,0
9,0,1,0,Part-time,Entry level,0,,0

In [43]:
df.tail()

,telecommuting,has_company_logo,has_questions,employment_type,required_experience,fraudulent,job_description,jd_word_count
17875,0,1,1,Full-time,Mid-Senior level,0,Account Director - Distribution Vend is looki...,861
17876,0,1,1,Full-time,Mid-Senior level,0,Payroll Accountant WebLinc is the e-commerce p...,658
17877,0,0,0,Full-time,Unknown,0,,0
17878,0,0,1,Contract,Not Applicable,0,,0
17879,0,1,1,Full-time,Mid-Senior level,0,,0

Finding unique values for Encoding

In [44]:
df.required_experience.unique()

array(['Internship', 'Not Applicable', 'Unknown', 'Mid-Senior level',
       'Associate', 'Entry level', 'Executive', 'Director'], dtype=object)

In [45]:
df.employment_type.unique()

array(['Other', 'Full-time', 'Unknown', 'Part-time', 'Contract',
       'Temporary'], dtype=object)

I used ordinal encoding for experience levels due to their inherent hierarchy and one-hot encoding for employment type to avoid imposing artificial order.

Ordinal Encoding

In [46]:
experience_mapping = {
    'Intership' : 0,
    'Entry level' : 1,
    'Associate' : 2,
    'Mid-Senior level' : 3,
    'Director' : 4,
    'Executive' : 5,
    'Not Applicable' : 6,
    'Unknown' : 6
}

df['req_exp_enc'] = df['required_experience'].map(experience_mapping)

One hot encoding

In [47]:
df = pd.get_dummies(df, columns=['employment_type'], drop_first=True)

In [48]:
df.head()

,telecommuting,has_company_logo,has_questions,required_experience,fraudulent,job_description,jd_word_count,req_exp_enc,employment_type_Full-time,employment_type_Other,employment_type_Part-time,employment_type_Temporary,employment_type_Unknown
0,0,1,0,Internship,0,,0,NaN,False,True,False,False,False
1,0,1,0,Not Applicable,0,Customer Service - Cloud Video Production 90 S...,901,6.0,True,False,False,False,False
2,0,1,0,Unknown,0,,0,6.0,False,False,False,False,True
3,0,1,0,Mid-Senior level,0,Account Executive - Washington DC Our passion ...,709,3.0,True,False,False,False,False
4,0,1,1,Mid-Senior level,0,Bill Review Manager SpotSource Solutions LLC i...,470,3.0,True,False,False,False,False

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   telecommuting              17880 non-null  int64
 1   has_company_logo           17880 non-null  int64
 2   has_questions              17880 non-null  int64
 3   required_experience        17880 non-null  object
 4   fraudulent                 17880 non-null  int64
 5   job_description            17880 non-null  object
 6   jd_word_count              17880 non-null  int64
 7   req_exp_enc                17499 non-null  float64
 8   employment_type_Full-time  17880 non-null  bool
 9   employment_type_Other      17880 non-null  bool
 10  employment_type_Part-time  17880 non-null  bool
 11  employment_type_Temporary  17880 non-null  bool
 12  employment_type_Unknown    17880 non-null  bool
dtypes: bool(5), float64(1), int64(5), object(2)
memory usage: 1.2+ MB

In [50]:
print('Before handling: ', df['req_exp_enc'].isna().sum())
df['req_exp_enc'] = df['req_exp_enc'].fillna(6)
print('After handling: ', df['req_exp_enc'].isna().sum())

Before handling:  381
After handling:  0

In [51]:
df.drop(columns=['required_experience'], inplace=True)
print("Dropped required_experience column")

Dropped required_experience column

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   telecommuting              17880 non-null  int64
 1   has_company_logo           17880 non-null  int64
 2   has_questions              17880 non-null  int64
 3   fraudulent                 17880 non-null  int64
 4   job_description            17880 non-null  object
 5   jd_word_count              17880 non-null  int64
 6   req_exp_enc                17880 non-null  float64
 7   employment_type_Full-time  17880 non-null  bool
 8   employment_type_Other      17880 non-null  bool
 9   employment_type_Part-time  17880 non-null  bool
 10  employment_type_Temporary  17880 non-null  bool
 11  employment_type_Unknown    17880 non-null  bool
dtypes: bool(5), float64(1), int64(5), object(1)
memory usage: 1.0+ MB

In [57]:
df.head(10)

,telecommuting,has_company_logo,has_questions,fraudulent,job_description,jd_word_count,req_exp_enc,employment_type_Full-time,employment_type_Other,employment_type_Part-time,employment_type_Temporary,employment_type_Unknown
0,0,1,0,0,,0,6.0,False,True,False,False,False
1,0,1,0,0,Customer Service - Cloud Video Production 90 S...,901,6.0,True,False,False,False,False
2,0,1,0,0,,0,6.0,False,False,False,False,True
3,0,1,0,0,Account Executive - Washington DC Our passion ...,709,3.0,True,False,False,False,False
4,0,1,1,0,Bill Review Manager SpotSource Solutions LLC i...,470,3.0,True,False,False,False,False
5,0,0,0,0,,0,6.0,False,False,False,False,True
6,0,1,1,0,"Head of Content (m/f) Founded in 2009, the Fon...",336,3.0,True,False,False,False,False
7,0,1,1,0,Lead Guest Service Specialist Airenvy’s mis...,710,6.0,False,False,False,False,True
8,0,1,1,0,,0,2.0,True,False,False,False,False
9,0,1,0,0,,0,1.0,False,False,True,False,False

In [58]:
# Saving this DataFrame for further processing
df.to_csv('../data/processed_data_v1.csv', index=False)
print('Processed data version 1 is saved.')

Processed data version 1 is saved.